// DecompileMsg5Functions.java — Ghidra headless script
// Decompiles functions related to the msg 5 handler (sub_FF85D3BC) and ring buffer access

import ghidra.app.decompiler.DecompInterface;
import ghidra.app.decompiler.DecompileResults;
import ghidra.app.script.GhidraScript;
import ghidra.program.model.address.Address;
import ghidra.program.model.listing.Function;
import ghidra.program.model.listing.FunctionManager;

import java.io.FileWriter;
import java.io.PrintWriter;

public class DecompileMsg5Functions extends GhidraScript {

    private static final long[][] FUNCTIONS = {
        { 0xFF93048CL, },  // Called by msg 5 to get first frame pointer and size
        { 0xFF930B04L, },  // Ring buffer initialization (called with base+0x200040)
        { 0xFF930B20L, },  // MOV container header writer
        { 0xFF8EDDFCL, },  // First frame encode/fetch (called with base+0x100040, size 0x19000)
        { 0xFF930F54L, },  // Gets SPS/PPS length
        { 0xFF9304B4L, },  // Gets SPS/PPS data
        { 0xFF9304C4L, },  // Gets additional SPS/PPS info
        { 0xFF930538L, },  // Gets buffer parameter
    };

    private static final String[] NAMES = {
        "FUN_ff93048c — Get first frame pointer and size (called by msg 5)",
        "FUN_ff930b04 — Ring buffer initialization (called with base+0x200040)",
        "FUN_ff930b20 — MOV container header writer",
        "FUN_ff8eddfc — First frame encode/fetch (called with base+0x100040, size 0x19000)",
        "FUN_ff930f54 — Gets SPS/PPS length",
        "FUN_ff9304b4 — Gets SPS/PPS data",
        "FUN_ff9304c4 — Gets additional SPS/PPS info",
        "FUN_ff930538 — Gets buffer parameter",
    };

    private static final String OUTPUT_FILE =
        "C:\\projects\\ixus870IS\\firmware-analysis\\msg5_functions_decompiled.txt";

    @Override
    public void run() throws Exception {
        PrintWriter out = new PrintWriter(new FileWriter(OUTPUT_FILE));
        out.println("=======================================================================");
        out.println("Msg 5 Ring Buffer Functions — Decompiled for IDR Capture Hook");
        out.println("Firmware: Canon IXUS 870 IS / SD880 IS, version 1.01a");
        out.println("Generated by DecompileMsg5Functions.java (Ghidra headless)");
        out.println("=======================================================================");
        out.println();

        FunctionManager funcMgr = currentProgram.getFunctionManager();
        DecompInterface decomp = new DecompInterface();
        decomp.openProgram(currentProgram);

        for (int i = 0; i < FUNCTIONS.length; i++) {
            long addr = FUNCTIONS[i][0];
            String desc = NAMES[i];
            Address funcAddr = currentProgram.getAddressFactory()
                .getDefaultAddressSpace().getAddress(addr);

            out.println("-----------------------------------------------------------------------");
            out.printf("Function %d/%d: %s%n", i + 1, FUNCTIONS.length, desc);
            out.printf("Address: 0x%08X%n", addr);
            out.println("-----------------------------------------------------------------------");

            Function func = funcMgr.getFunctionAt(funcAddr);
            if (func == null) {
                disassemble(funcAddr);
                func = createFunction(funcAddr, null);
            }

            if (func == null) {
                out.println("[ERROR] Could not create function at this address.");
                out.println();
                continue;
            }

            out.printf("Function name in Ghidra: %s%n", func.getName());
            out.printf("Function size: %d bytes%n",
                func.getBody().getNumAddresses());
            out.println();

            DecompileResults results = decomp.decompileFunction(func, 120, monitor);
            if (results.decompileCompleted()) {
                out.println(results.getDecompiledFunction().getC());
            } else {
                out.println("[ERROR] Decompilation failed: " + results.getErrorMessage());
            }
            out.println();
        }

        decomp.dispose();
        out.close();
        println("DecompileMsg5Functions: Output written to " + OUTPUT_FILE);
    }
}
